/// @file scanners/autogen_oauth_2_0_oidc_deep_15.cpp
/// @brief Auto-generated scanner: OAuth 2.0 / OIDC Deep (15)
///        Checks: OIDC nonce replay attack, OIDC logout redirect manipulat
#include "scanner_base.hpp"
#include <regex>
#include <chrono>

namespace apex {
namespace {

/// OIDC nonce replay attack
std::vector<Finding> scan_oidc_nonce_replay_attack(const Config &, HttpClient &http,
                                       const CrawlResult &crawl) {
  std::vector<Finding> findings;
  if (crawl.urls.empty()) return findings;
  std::string base = base_url_from(crawl.urls[0]);

  // OIDC nonce replay attack
  // TODO: Implement specific check for: OIDC nonce replay attack
  // This is a placeholder generated by auto-expand.py

  return findings;
}

/// OIDC logout redirect manipulation
std::vector<Finding> scan_oidc_logout_redirect_manipulation(const Config &, HttpClient &http,
                                       const CrawlResult &crawl) {
  std::vector<Finding> findings;
  if (crawl.urls.empty()) return findings;
  std::string base = base_url_from(crawl.urls[0]);

  // OIDC logout redirect manipulation
  for (const auto &url : crawl.urls) {
    if (url.find("redirect") == std::string::npos && url.find("next") == std::string::npos) continue;
    auto resp = http.get(url + "https://evil.com");
    if (resp.status_code == 302) {
      auto loc = resp.headers.find("Location");
      if (loc != resp.headers.end() && loc->second.find("evil.com") != std::string::npos) {
        findings.push_back(Finding{"OIDC logout redirect manipulation", "medium", url,
                            "Open redirect confirmed",
                            "", "https://evil.com", "Location: " + loc->second});
        return findings;
      }
    }
    break;
  }

  return findings;
}


} // namespace

std::vector<Scanner> register_autogen_oauth_2_0_oidc_deep_15_scanners() {
  return {
      {"OIDC nonce replay attack", scan_oidc_nonce_replay_attack},
      {"OIDC logout redirect manipulation", scan_oidc_logout_redirect_manipulation},
  };
}

} // namespace apex
