/// @file scanners/autogen_next_js_react_deep_15.cpp
/// @brief Auto-generated scanner: Next.js / React Deep (15)
///        Checks: Next.js build manifest exposur, React state serialization inje, Next.js revalidation path pois, Next.js preview mode bypass, React useEffect side-channel
#include "scanner_base.hpp"
#include <regex>
#include <chrono>

namespace apex {
namespace {

/// Next.js build manifest exposure
std::vector<Finding> scan_next_js_build_manifest_exposure(const Config &, HttpClient &http,
                                       const CrawlResult &crawl) {
  std::vector<Finding> findings;
  if (crawl.urls.empty()) return findings;
  std::string base = base_url_from(crawl.urls[0]);

  // Next.js build manifest exposure
  // TODO: Implement specific check for: Next.js build manifest exposure
  // This is a placeholder generated by auto-expand.py

  return findings;
}

/// React state serialization injection
std::vector<Finding> scan_react_state_serialization_injection(const Config &, HttpClient &http,
                                       const CrawlResult &crawl) {
  std::vector<Finding> findings;
  if (crawl.urls.empty()) return findings;
  std::string base = base_url_from(crawl.urls[0]);

  // React state serialization injection
  // TODO: Implement specific check for: React state serialization injection
  // This is a placeholder generated by auto-expand.py

  return findings;
}

/// Next.js revalidation path poisoning
std::vector<Finding> scan_next_js_revalidation_path_poisoning(const Config &, HttpClient &http,
                                       const CrawlResult &crawl) {
  std::vector<Finding> findings;
  if (crawl.urls.empty()) return findings;
  std::string base = base_url_from(crawl.urls[0]);

  // Next.js revalidation path poisoning
  // TODO: Implement specific check for: Next.js revalidation path poisoning
  // This is a placeholder generated by auto-expand.py

  return findings;
}

/// Next.js preview mode bypass
std::vector<Finding> scan_next_js_preview_mode_bypass(const Config &, HttpClient &http,
                                       const CrawlResult &crawl) {
  std::vector<Finding> findings;
  if (crawl.urls.empty()) return findings;
  std::string base = base_url_from(crawl.urls[0]);

  // Next.js preview mode bypass
  auto resp = http.get(base + "/admin");
  if (resp.status_code == 403 || resp.status_code == 401) {
    // Try bypass
    auto bypass = http.get(base + "/admin", {{"X-Original-URL", "/admin"}});
    if (bypass.status_code == 200 && bypass.body.size() > 200 &&
        bypass.body.find("{") == 0) {
      findings.push_back(Finding{"Next.js preview mode bypass", "critical", base + "/admin",
                          "Access control bypass successful",
                          "", "X-Original-URL", bypass.body.substr(0, 150)});
    }
  }

  return findings;
}

/// React useEffect side-channel
std::vector<Finding> scan_react_useeffect_side_channel(const Config &, HttpClient &http,
                                       const CrawlResult &crawl) {
  std::vector<Finding> findings;
  if (crawl.urls.empty()) return findings;
  std::string base = base_url_from(crawl.urls[0]);

  // React useEffect side-channel
  // TODO: Implement specific check for: React useEffect side-channel
  // This is a placeholder generated by auto-expand.py

  return findings;
}


} // namespace

std::vector<Scanner> register_autogen_next_js_react_deep_15_scanners() {
  return {
      {"Next.js build manifest exposure", scan_next_js_build_manifest_exposure},
      {"React state serialization injection", scan_react_state_serialization_injection},
      {"Next.js revalidation path poisoning", scan_next_js_revalidation_path_poisoning},
      {"Next.js preview mode bypass", scan_next_js_preview_mode_bypass},
      {"React useEffect side-channel", scan_react_useeffect_side_channel},
  };
}

} // namespace apex
