/// @file scanners/autogen_request_tunneling_attacks_12.cpp
/// @brief Auto-generated scanner: Request Tunneling Attacks (12)
///        Checks: Request tunnel via CONNECT met, Request tunnel in proxy chain , Request tunnel for internal po, Request tunnel through load ba, Request tunnel through OPTIONS
#include "scanner_base.hpp"
#include <regex>
#include <chrono>

namespace apex {
namespace {

/// Request tunnel via CONNECT method proxy abuse
std::vector<Finding> scan_request_tunnel_via_connect_method_proxy_(const Config &, HttpClient &http,
                                       const CrawlResult &crawl) {
  std::vector<Finding> findings;
  if (crawl.urls.empty()) return findings;
  std::string base = base_url_from(crawl.urls[0]);

  // Request tunnel via CONNECT method proxy abuse
  // TODO: Implement specific check for: Request tunnel via CONNECT method proxy abuse
  // This is a placeholder generated by auto-expand.py

  return findings;
}

/// Request tunnel in proxy chain exploitation technique
std::vector<Finding> scan_request_tunnel_in_proxy_chain_exploitati(const Config &, HttpClient &http,
                                       const CrawlResult &crawl) {
  std::vector<Finding> findings;
  if (crawl.urls.empty()) return findings;
  std::string base = base_url_from(crawl.urls[0]);

  // Request tunnel in proxy chain exploitation technique
  // TODO: Implement specific check for: Request tunnel in proxy chain exploitation technique
  // This is a placeholder generated by auto-expand.py

  return findings;
}

/// Request tunnel for internal port scanning discovery
std::vector<Finding> scan_request_tunnel_for_internal_port_scannin(const Config &, HttpClient &http,
                                       const CrawlResult &crawl) {
  std::vector<Finding> findings;
  if (crawl.urls.empty()) return findings;
  std::string base = base_url_from(crawl.urls[0]);

  // Request tunnel for internal port scanning discovery
  // TODO: Implement specific check for: Request tunnel for internal port scanning discovery
  // This is a placeholder generated by auto-expand.py

  return findings;
}

/// Request tunnel through load balancer bypass technique
std::vector<Finding> scan_request_tunnel_through_load_balancer_byp(const Config &, HttpClient &http,
                                       const CrawlResult &crawl) {
  std::vector<Finding> findings;
  if (crawl.urls.empty()) return findings;
  std::string base = base_url_from(crawl.urls[0]);

  // Request tunnel through load balancer bypass technique
  auto resp = http.get(base + "/admin");
  if (resp.status_code == 403 || resp.status_code == 401) {
    // Try bypass
    auto bypass = http.get(base + "/admin", {{"X-Original-URL", "/admin"}});
    if (bypass.status_code == 200 && bypass.body.size() > 200 &&
        bypass.body.find("{") == 0) {
      findings.push_back(Finding{"Request tunnel through load balancer bypass technique", "critical", base + "/admin",
                          "Access control bypass successful",
                          "", "X-Original-URL", bypass.body.substr(0, 150)});
    }
  }

  return findings;
}

/// Request tunnel through OPTIONS pre-flight abuse
std::vector<Finding> scan_request_tunnel_through_options_pre_fligh(const Config &, HttpClient &http,
                                       const CrawlResult &crawl) {
  std::vector<Finding> findings;
  if (crawl.urls.empty()) return findings;
  std::string base = base_url_from(crawl.urls[0]);

  // Request tunnel through OPTIONS pre-flight abuse
  // TODO: Implement specific check for: Request tunnel through OPTIONS pre-flight abuse
  // This is a placeholder generated by auto-expand.py

  return findings;
}


} // namespace

std::vector<Scanner> register_autogen_request_tunneling_attacks_12_scanners() {
  return {
      {"Request tunnel via CONNECT method proxy abuse", scan_request_tunnel_via_connect_method_proxy_},
      {"Request tunnel in proxy chain exploitation technique", scan_request_tunnel_in_proxy_chain_exploitati},
      {"Request tunnel for internal port scanning discovery", scan_request_tunnel_for_internal_port_scannin},
      {"Request tunnel through load balancer bypass technique", scan_request_tunnel_through_load_balancer_byp},
      {"Request tunnel through OPTIONS pre-flight abuse", scan_request_tunnel_through_options_pre_fligh},
  };
}

} // namespace apex
